apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: v1
kind: Service
metadata:
  name: llama
  labels:
    app: llama
  namespace: llm
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: llama

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
  namespace: llm
spec:
  selector:
    matchLabels:
      app: llama
  replicas: 1
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: registry.gitlab.com/f5-public/llama-cpp-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: llama
  namespace: llm
spec:
  policy:
    enforcementMode: blocking
    name: llama
    description: NGINX App Protect WAF API Security Policy for the OpenAI
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    open-api-files:
    - link: https://gitlab.com/f5-public/llama-cpp-python/-/raw/main/OpenAI-Swagger.yaml
    blocking-settings:
      violations:
      - block: true
        description: Disallowed file upload content detected in body
        name: VIOL_FILE_UPLOAD_IN_BODY
      - block: true
        description: Mandatory request body is missing
        name: VIOL_MANDATORY_REQUEST_BODY
      - block: true
        description: Illegal parameter location
        name: VIOL_PARAMETER_LOCATION
      - block: true
        description: Mandatory parameter is missing
        name: VIOL_MANDATORY_PARAMETER
      - block: true
        description: JSON data does not comply with JSON schema
        name: VIOL_JSON_SCHEMA
      - block: true
        description: Illegal parameter array value
        name: VIOL_PARAMETER_ARRAY_VALUE
      - block: true
        description: Illegal Base64 value
        name: VIOL_PARAMETER_VALUE_BASE64
      - block: true
        description: Disallowed file upload content detected
        name: VIOL_FILE_UPLOAD
      - block: true
        description: Illegal request content type
        name: VIOL_URL_CONTENT_TYPE
      - block: true
        description: Illegal static parameter value
        name: VIOL_PARAMETER_STATIC_VALUE
      - block: true
        description: Illegal parameter value length
        name: VIOL_PARAMETER_VALUE_LENGTH
      - block: true
        description: Illegal parameter data type
        name: VIOL_PARAMETER_DATA_TYPE
      - block: true
        description: Illegal parameter numeric value
        name: VIOL_PARAMETER_NUMERIC_VALUE
      - block: true
        description: Parameter value does not comply with regular expression
        name: VIOL_PARAMETER_VALUE_REGEXP
      - block: true
        description: Illegal URL
        name: VIOL_URL
      - block: true
        description: Illegal parameter
        name: VIOL_PARAMETER
      - block: true
        description: Illegal empty parameter value
        name: VIOL_PARAMETER_EMPTY_VALUE
      - block: true
        description: Illegal repeated parameter name
        name: VIOL_PARAMETER_REPEATED

---
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: logconf
  namespace: llm
spec:
  filter:
    request_type: all
  content:
    format: default
    max_request_size: any
    max_message_size: 5k

---
apiVersion: appprotectdos.f5.com/v1beta1
kind: APDosPolicy
metadata:
  name: dospolicy
  namespace: llm
spec:
  mitigation_mode: "conservative"
  signatures: "on"
  bad_actors: "off"
  automation_tools_detection: "off"
  tls_fingerprint: "off"

---
apiVersion: appprotectdos.f5.com/v1beta1
kind: APDosLogConf
metadata:
   name: doslogconf
   namespace: llm
spec:
   filter:
      traffic-mitigation-stats: all
      bad-actors: top 10
      attack-signatures: top 10

---
apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
  name: dos-protected
  namespace: llm
spec:
  enable: true
  name: "llama"
  apDosPolicy: "llm/dospolicy"
  apDosMonitor:
    uri: "http://llama:8000/v1/completions"
    protocol: "http1"
    timeout: 5
  dosSecurityLog:
    enable: true
    apDosLogConf: "llm/doslogconf"
    dosLogDest: "10.0.134.70:5261"


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama
  namespace: llm
  annotations:
    appprotect.f5.com/app-protect-policy: "llm/llama"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "llm/logconf"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=10.0.134.70:5261"
    appprotectdos.f5.com/app-protect-dos-resource: "llm/dos-protected"
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: llama
      port:
        number: 8000
  rules:
  - host: "*.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: llama
            port:
              number: 8000
